POST http://localhost:5001/api/auth/signup
Content-Type: application/json

{
    "username": "Favour",
  "email": "fezeugwa@pvamu.edu",
  "password": "password1234"
}

###
POST http://localhost:5001/api/auth//resend-otp
Content-Type: application/json

{
  "email": "fezeugwa@pvamu.edu"
}

###
POST http://localhost:5001/api/auth/verify-otp
Content-Type: application/json

{
  "email": "fezeugwa@pvamu.edu",
  "otp": "346618"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "fezeugwa@pvamu.edu",
  "password": "password1234"
}

