POST http://localhost:5001/api/auth/signup
Content-Type: application/json

{
    "username": "Ud",
  "email": "uigwenagu@pvamu.edu",
  "password": "password1234"
}

###
POST http://localhost:5001/api/auth//forgot-password
Content-Type: application/json

{
  "email": "uigwenagu@pvamu.edu"
}

###
POST http://localhost:5001/api/auth/reset-password/925179?email=uigwenagu@pvamu.edu
Content-Type: application/json

{
  "newPassword": "password1234"
}

###
POST http://localhost:5001/api/auth/resend-otp
Content-Type: application/json

{
  "email": "uigwenagu@pvamu.edu"
}

###
POST http://localhost:5001/api/auth/verify-otp
Content-Type: application/json

{
  "email": "uigwenagu@pvamu.edu",
  "otp": "769945"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "email": "fezeugwa@pvamu.edu",
  "password": "123456"
}

###
POST http://localhost:5001/api/carpool/create-carpool
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU1NTFlNTE1ZTkwYWUyYmFjNGM0YiIsImlhdCI6MTczMTI4NzE4MiwiZXhwIjoxNzMxMjkwNzgyfQ.bOeR4eYD2d0vWc7uOlKWm7mvKZ4oFTXFFpb7Xn9gD6g

{
  "carpoolName": "Fav's Nails Carpool",
      "pickupLocation": "Fountain Hill",
      "dropoffLocation": "Nails and Spa",
      "dateTime": "2024-11-19T14:00:00Z",
      "role": "Rider",
      "carType": "Rental",
      "isPublic": true,
      "maxCarpoolers": 4,
      "estimatedCost": "30",
      "specialNotes": "My carpool",
      "invitations": []
}

###
GET http://localhost:5001/api/carpool/public-carpools
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWU1NTFlNTE1ZTkwYWUyYmFjNGM0YiIsImlhdCI6MTczMTI4NzE4MiwiZXhwIjoxNzMxMjkwNzgyfQ.bOeR4eYD2d0vWc7uOlKWm7mvKZ4oFTXFFpb7Xn9gD6g